exception raises if no browser is set or browser.name is set to a script
  File "/home/xupeng/dev/douban/codecli/codecli/utils.py", line 222, in browser_open
    check_call([browser, url])
UnboundLocalError: local variable 'browser' referenced before assignment